mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examine?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8090

